services:
  api:
    build:
      context: ..
      dockerfile: build/package/Dockerfile
    container_name: service_auth
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT-5432}
      AUTH_HOST: api
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - path: ../config/.env
        required: false
    ports:
      - "${AUTH_PORT-9090}:${AUTH_PORT-9090}"
    secrets:
      - jwt_secret

  postgres:
    image: postgres:18.3-alpine3.23
    container_name: pg_auth
    environment:
      POSTGRES_USER: ${POSTGRES_USER-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-admin}
      POSTGRES_DB: ${POSTGRES_DB-auth}
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - pg_auth_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d auth -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - path: ../config/.env
        required: false
    ports:
      - "5440:5432"

volumes:
  pg_auth_data:

secrets:
  jwt_secret:
    file: ${JWT_SECRET_PATH-../config/jwt.secret.txt}
